CREATE TABLE sky_group(
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL,
  owner VARCHAR(50) NOT NULL,
  category INT DEFAULT 0 ,
  logo VARCHAR(200),
  description TEXT,
  openness TINYINT NOT NULL,
  createTime DATETIME NOT NULL);


CREATE TABLE sky_groupuser(
  id INT PRIMARY KEY AUTO_INCREMENT,
  groupId INT NOT NULL ,
  userName VARCHAR(50) NOT NULL,
  nickName VARCHAR(50) NOT NULL,
  joinTime DATETIME NOT NULL
);

